-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 13:54:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema odznaki
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`lancuchy_gorskie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lancuchy_gorskie` (
  `id_lancuchy_gorskie` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lancuchy_gorskie`))
ENGINE = InnoDB;
select * from lancuchy_gorskie;

-- -----------------------------------------------------
-- Table `mydb`.`pasma_gorskie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pasma_gorskie` (
  `id_pasma_gorskie` INT NOT NULL AUTO_INCREMENT,
  `nazwa_pasma` VARCHAR(45) NOT NULL,
  `lancuchy_gorskie_id_lancuchy_gorskie` INT NOT NULL,
  PRIMARY KEY (`id_pasma_gorskie`, `lancuchy_gorskie_id_lancuchy_gorskie`),
  INDEX `fk_pasma_gorskie_lancuchy_gorskie_idx` (`lancuchy_gorskie_id_lancuchy_gorskie` ASC),
  CONSTRAINT `fk_pasma_gorskie_lancuchy_gorskie`
    FOREIGN KEY (`lancuchy_gorskie_id_lancuchy_gorskie`)
    REFERENCES `mydb`.`lancuchy_gorskie` (`id_lancuchy_gorskie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pasma_szczyty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pasma_szczyty` (
  `id_pasma_szczyty` INT NOT NULL AUTO_INCREMENT,
  `nazwa_szczytu` VARCHAR(45) NOT NULL,
  `wysokosc` INT NOT NULL,
  `pasma_gorskie_id_pasma_gorskie` INT NOT NULL,
  `kgp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pasma_szczyty`, `pasma_gorskie_id_pasma_gorskie`),
  INDEX `fk_szczyty_pasma_gorskie1_idx` (`pasma_gorskie_id_pasma_gorskie` ASC),
  CONSTRAINT `fk_szczyty_pasma_gorskie1`
    FOREIGN KEY (`pasma_gorskie_id_pasma_gorskie`)
    REFERENCES `mydb`.`pasma_gorskie` (`id_pasma_gorskie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`urzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`urzytkownicy` (
  `id_urzytkownicy` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_urzytkownicy`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`odznaki_pasma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`odznaki_pasma` (
  `id_odznaki` INT NOT NULL AUTO_INCREMENT,
  `stopien` VARCHAR(45) NOT NULL,
  `liczba_szczytow` VARCHAR(45) NOT NULL,
  `pasma_gorskie_id_pasma_gorskie` INT NOT NULL,
  PRIMARY KEY (`id_odznaki`, `pasma_gorskie_id_pasma_gorskie`),
  INDEX `fk_odznaki_pasma_pasma_gorskie1_idx` (`pasma_gorskie_id_pasma_gorskie` ASC),
  CONSTRAINT `fk_odznaki_pasma_pasma_gorskie1`
    FOREIGN KEY (`pasma_gorskie_id_pasma_gorskie`)
    REFERENCES `mydb`.`pasma_gorskie` (`id_pasma_gorskie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`osiagniecia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`osiagniecia` (
  `id_osiagniecia` INT NOT NULL AUTO_INCREMENT,
  `data_wycieczki` DATE NOT NULL,
  `urzytkownicy_id_urzytkownicy` INT NOT NULL,
  `pasma_szczyty_id_pasma_szczyty` INT NOT NULL,
  PRIMARY KEY (`id_osiagniecia`, `urzytkownicy_id_urzytkownicy`, `pasma_szczyty_id_pasma_szczyty`),
  INDEX `fk_osiagniecia_urzytkownicy1_idx` (`urzytkownicy_id_urzytkownicy` ASC),
  INDEX `fk_osiagniecia_pasma_szczyty1_idx` (`pasma_szczyty_id_pasma_szczyty` ASC),
  CONSTRAINT `fk_osiagniecia_urzytkownicy1`
    FOREIGN KEY (`urzytkownicy_id_urzytkownicy`)
    REFERENCES `mydb`.`urzytkownicy` (`id_urzytkownicy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_osiagniecia_pasma_szczyty1`
    FOREIGN KEY (`pasma_szczyty_id_pasma_szczyty`)
    REFERENCES `mydb`.`pasma_szczyty` (`id_pasma_szczyty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`odznaki_uzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`odznaki_uzytkownicy` (
  `id_odznaki_uzytkownicy` INT NOT NULL AUTO_INCREMENT,
  `urzytkownicy_id_urzytkownicy` INT NOT NULL,
  `odznaki_pasma_id_odznaki` INT NOT NULL,
  `odznaka_kgp` INT NOT NULL,
  PRIMARY KEY (`id_odznaki_uzytkownicy`, `urzytkownicy_id_urzytkownicy`, `odznaki_pasma_id_odznaki`),
  INDEX `fk_odznaki_uzytkownicy_urzytkownicy1_idx` (`urzytkownicy_id_urzytkownicy` ASC),
  INDEX `fk_odznaki_uzytkownicy_odznaki_pasma1_idx` (`odznaki_pasma_id_odznaki` ASC),
  CONSTRAINT `fk_odznaki_uzytkownicy_urzytkownicy1`
    FOREIGN KEY (`urzytkownicy_id_urzytkownicy`)
    REFERENCES `mydb`.`urzytkownicy` (`id_urzytkownicy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odznaki_uzytkownicy_odznaki_pasma1`
    FOREIGN KEY (`odznaki_pasma_id_odznaki`)
    REFERENCES `mydb`.`odznaki_pasma` (`id_odznaki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
